### PR TITLE
Fix Gibbon\Forms\Layout\Row::__call magic method issue hanlding error output of actually called function

### LINKED ISSUE #1227: Gibbon\Forms\Layout\Row::__call() unable to handle proxy function returning null
**Describe the bug**
* `Gibbon\Forms\Layout\Row::__call()` magic method unable to handle the case where the proxy function call return anything other than a `Gibbon\Forms\OutputableInterface` (e.g. `null`).

**To Reproduce**
Saw this error in CI environment. The exact step to reproduce is not yet indentified.

**Expected behavior**
Such error should be elegantly handled.

**Screenshots**
2021-01-27 23-06-07 的螢幕擷圖

**Your System**

 - Gibbon version: v22.0.00 latest
 - Browser: PhpBrowser of Codeception

### PR DESCRIPTION
**Pull request by yookoala**
**Description**
* Properly handle the case when function returned anything other than `Gibbon\Forms\OutputableInterface`.
* Properly rewrite the error messages from sprintf to __().

**Motivation and Context**
* Fix #1227.

**How Has This Been Tested?**
CI Environment

**Screenshots**
2021-01-27 23-06-07 的螢幕擷圖

### CODE REVIEW

File: src/Forms/Layout/Row.php [hunk 1]
```diff
@@ -70,10 +70,23 @@ public function __call($function, $args)
                 $element->setRow($this);
             }
         } catch (\ReflectionException $e) {
-            $element = $this->factory->createContent(sprintf('Cannot %1$s. This form element does not exist in the current FormFactory', $function).': '.$e->getMessage());
+            $element = $this->factory->createContent(__('Cannot {function}. This form element does not exist in the current FormFactory: ', [
+                'function' => $function,
+                'message' => $e->getMessage(),
+            ]));
```
Comment (SKuipers) [inline src/Forms/Layout/Row.php:76]:
```suggestion
            $element = $this->factory->createContent(strtr('Cannot {function}. This form element does not exist in the current FormFactory: {message}', [
                '{function}' => $function,
                '{message}' => $e->getMessage(),
            ]));
```

File: src/Forms/Layout/Row.php [hunk 2]
```diff
@@ -70,10 +70,23 @@ public function __call($function, $args)
...
         } catch (\Exception $e) {
-            $element = $this->factory->createContent(sprintf('Cannot %1$s. Error creating form element.', $function).': '.$e->getMessage());
+            $element = $this->factory->createContent(__('Cannot {function}. Error creating form element: {message}', [
+                'function' => $function,
+                'message' => $e->getMessage(),
+            ]));
```
Comment (SKuipers) [inline src/Forms/Layout/Row.php:81]:
```suggestion
            $element = $this->factory->createContent(strtr('Cannot {function}. Error creating form element: {message}', [
                '{function}' => $function,
                '{message}' => $e->getMessage(),
            ]));
```

File: src/Forms/Layout/Row.php [hunk 3]
```diff
@@ -70,10 +70,23 @@ public function __call($function, $args)
...
         } finally {
+            if (!($element instanceof OutputableInterface)) {
+                if (($element_type = gettype($element)) === 'object') $element_type = get_class($element);
+                $element = $this->factory->createContent(__('{function} returned {type} instead of an outputable form element.', [
+                    'type' => $element_type,
+                    'function' => $function,
+                ]));
```
Comment (SKuipers) [inline src/Forms/Layout/Row.php:88]:
```suggestion
                $element = $this->factory->createContent(strtr('{function} returned {type} instead of an outputable form element.', [
                    '{type}' => $element_type,
                    '{function}' => $function,
                ]));
```

**Review by SKuipers — APPROVED** [review]
Hi Koala, thanks for catching this and improving the error messages. I think I'd rather not create interface strings for these, which adds to the translation burden, when these errors would generally only be seen in development. I've updated them to use strtr, which preserves the named placeholders you've added. I'm going to merge and test. Thanks!
